package com.okaynow.notifications.domain;

public enum NotificationType {
    SHIFT_DRAFT_CREATED,
    SHIFT_POSTED,
    SHIFT_CLAIMED,
    SHIFT_ASSIGNED,
    SHIFT_CONFIRMED,
    SHIFT_RELEASED,
    SHIFT_HELD,
    SHIFT_CANCELLED,
    SHIFT_STARTED,
    SHIFT_COMPLETED,
    SHIFT_EXTENDED,
    SHIFT_REPLACEMENT_REQUESTED,
    CAREGIVER_REJECTED_BY_CLIENT,
    SHIFT_NO_SHOW,
    PLATFORM_CONVERSION_FEE,
    VISIT_CLOCK_IN,
    VISIT_CLOCK_OUT,
    VISIT_ARRIVAL_CONFIRMED,
    INVOICE_SENT,
    SYSTEM
}
